geodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('macacoprego/', admin.site.urls),
    path('api/', include('markers.api')),
    path('', include('markers.urls')),
    path('posts/', include('posts.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markers/urls.py
from django.urls import path
from markers.views import MarkersMapView

app_name = "markers"

# Definição das URLs para o aplicativo 'markers'
urlpatterns = [
    path("", MarkersMapView.as_view(), name='markersmapview'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

# URL patterns para a aplicação posts
urlpatterns = [
    # Rota para exibir detalhes de um post específico
    path('p/<int:pk>/', views.detalhes_post, name='post-detail')
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
from django.utils import timezone

# Modelo representando temas de conflitos ambientais
class Tema(models.Model):
    nome = models.CharField('Tema', max_length=255, help_text="Especifique o tema do Conflito Ambiental")
    
    class Meta:
        verbose_name_plural = 'Temas'

    def __str__(self):
        return self.nome

# Modelo representando os municípios atingidos
class Municipio(models.Model):
    nome = models.CharField('Município Atingido', max_length=255, help_text="Digite o município atingido")

    class Meta:
        verbose_name_plural = 'Municípios Atingidos'

    def __str__(self):
        return self.nome

# Modelo representando os atores envolvidos
class Ator(models.Model):
    nome = models.CharField('Atores envolvidos', max_length=255, help_text="Digite os atores envolvidos")
    
    class Meta:
        verbose_name_plural = 'Atores envolvidos'

    def __str__(self):
        return self.nome

# Modelo representando as populações atingidas
class Populacao(models.Model):
    nome = models.CharField('Populações atingidas', max_length=255, help_text="Especifique a população atingida")

    class Meta:
        verbose_name_plural = 'Populações Atingidas'

    def __str__(self):
        return self.nome

# Modelo representando uma publicação (Post)
class Post(models.Model):
    titulo = models.CharField(max_length=255, help_text="Escreva um título para a sua publicação")
    autor = models.CharField(max_length=255, help_text="Digite os autores da publicação")
    data_publicacao = models.DateTimeField(auto_now_add=True)
    atualizacao_publicacao = models.DateTimeField(auto_now=True)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)
    municipio_atingido = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    atores_envolvidos = models.ForeignKey(Ator, on_delete=models.CASCADE)
    populacao_atingida = models.ForeignKey(Populacao, on_delete=models.CASCADE)
    conteudo = CKEditor5Field('Conteúdo', config_name='extends')  # Campo de texto rico usando CKEditor
    fontes = CKEditor5Field('Fontes', config_name='extends')  # Outro campo de texto rico para fontes

    class Meta:
        verbose_name_plural = 'Publicações'

    def __str__(self):
        # Função para exibir o título e autor truncados, se necessário
        max_titulo_length = 50  # Defina o comprimento máximo desejado para o título
        max_autor_length = 50   # Defina o comprimento máximo desejado para o autor

        # Limitando o título
        titulo_str = (self.titulo[:max_titulo_length] + '...') if len(self.titulo) > max_titulo_length else self.titulo

        # Limitando o autor
        autor_str = (self.autor[:max_autor_length] + '...') if len(self.autor) > max_autor_length else self.autor

        return titulo_str + ' | ' + autor_str

    # Funções para formatar datas de publicação e atualização
    def data_publicacao_formatada(self):
        return self.data_publicacao.strftime('%d/%m/%Y')
    
    def data_atualizacao_formatada(self):
        return self.atualizacao_publicacao.strftime('%d/%m/%Y')

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

# View para exibir detalhes de um post específico
def detalhes_post(request, pk):
    # Recupera o post pelo ID (pk) ou retorna 404 se não for encontrado
    post = get_object_or_404(Post, pk=pk)
    # Renderiza o template 'detalhes_post.html' com o contexto do post
    return render(request, 'posts/detalhes_post.html', {'post': post})

posts/templates/posts/detalhes_post.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <link rel="icon" type="image/x-icon" href="{% static '/assets/Logo.svg' %}">
    <title>{{ post.titulo }}</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Leaflet CSS and JS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

    <!-- Marker Cluster CSS and JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.Default.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/leaflet.markercluster.js"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/stylepost.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary p-4 fixed-top">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center" href="{% url 'markers:markersmapview' %}">
                    <img class="navbar-logo me-3" src="{% static '/assets/Logo.svg' %}" alt="Logo EcoLagos">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" id="home-menu" aria-current="page" href="{% url 'markers:markersmapview' %}">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="team-menu" href="{% url 'markers:markersmapview' %}">Sobre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="about-menu" href="{% url 'markers:markersmapview' %}">Equipe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="contact-menu" href="{% url 'markers:markersmapview' %}">Contate-nos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>    
    </header>

    <main>
        <h1>{{ post.titulo }}</h1>
        <small>
            <p>Escrito por: {{ post.autor }}</p>
            <p>Publicado em: {{ post.data_publicacao_formatada }}</p>
            <p>Última atualização: {{ post.data_atualizacao_formatada }}</p>
        </small>
        <div class="info-container">
            <div class="info-box">
                <h2>Tema</h2>
                <p>{{ post.tema }}</p>
            </div>
            <div class="info-box">
                <h2>Município Atingido</h2>
                <p>{{ post.municipio_atingido }}</p>
            </div>
            <div class="info-box">
                <h2>Atores Envolvidos</h2>
                <p>{{ post.atores_envolvidos }}</p>
            </div>
            <div class="info-box">
                <h2>População Atingida</h2>
                <p>{{ post.populacao_atingida }}</p>
            </div>
        </div>    
        <div class="post-content">
            {{ post.conteudo | safe}}
        </div>
        <h2>Fontes</h2>
        <p>{{ post.fontes | safe}}</p>
    </main>

    <!-- Footer (optional) -->
    <footer class="p-3">
        <p class="text-center">EcoLagos &copy; 2023. Todos os direitos reservados.</p>
    </footer>
    
</body>

</html>